version: '3.9'

services:

  web:
    build: .
    container_name: ml-fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - .env:/app/.env:ro
      - ./models:/app/models
      - ./uploads:/app/uploads
    networks:
      - app-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

